VARIABLE'S IN PYTHON

In [1]:
x = 5
y = "John"
print(x)
print(y)

5
John


In [2]:
x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0

In [3]:
print(x,y,z)

3 3 3.0


In [4]:
print(x+3)

TypeError: can only concatenate str (not "int") to str

In [5]:
print(y+3)

6


In [6]:
print(x+'3')

33


Use of type() function
genrally type function is used to find which type of variable is their 

In [7]:
print(type(x))

<class 'str'>


In [8]:
print(type(y))

<class 'int'>


Concept of local and global variable 

In [11]:
y = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()
print("Python is " + y)


Python is fantastic
Python is awesome


In [12]:
y = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()
print("Python is " + y)
print("Python is " + x)

Python is fantastic
Python is awesome
Python is 3


In [13]:
y = "awesome"

def myfunc():
  global x
  x = "fantastic"
  print("Python is " + x)

myfunc()
print("Python is " + y)
print("Python is " + x)

Python is fantastic
Python is awesome
Python is fantastic


TYPECASTING OF VARIABLES 

In [15]:
a=10 #here automatically a becomes a integer

In [16]:
print(str(a))

10


In [17]:
print(float(a))

10.0


Lists in python 

USE OF PRINT AND INPUT STATEMENTS 

In [18]:
print('10')#this is for a value 10 
a=5
print(a)


10
5


In [19]:
a=input("enter value of a")#default type of input is string 
print(type(a))

<class 'str'>


In [20]:
a=int(a)
print(type(a))

<class 'int'>


In [35]:
mylist = ["apple",1, "cherry"]
# print(type(mylist[1]))

<class 'int'>


In [22]:
thislist = ["apple", "banana", "cherry"]
print(thislist)

['apple', 'banana', 'cherry']


In [ ]:
print(len(thislist))
print(type(thislist))

In [23]:
print(thislist[1])

banana


In [24]:
print(thislist[-1])

cherry


In [25]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])

['cherry', 'orange', 'kiwi']


TUPPLE 

In [26]:
thistuple = ("apple", "banana", "cherry")
print(thistuple)

('apple', 'banana', 'cherry')


In [27]:
print(len(thistuple))

3


In [28]:
print(type(tuple))

<class 'type'>


In [29]:
print(thistuple[1])

banana


CONTROLL STATEMENTS 

In [31]:
a = 33
b = 200
if b > a:
  print("b is greater than a")

b is greater than a


In [32]:
a = 33
b = 200
if b > a:
  print("b is greater than a")
else:
  print('a greater than b')

b is greater than a


In [ ]:
a = 33
b = 200
if b > a:
  print("b is greater than a")
elif(b==a):
    print("b is equal to a ")
else:
  print('a greater than b')

LOOPS 

The while Loop
With the while loop we can execute a set of statements as long as a condition is true.

In [ ]:
i = 1
while i < 6:
  print(i)
  i += 1

The break Statement

In [36]:
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3


The continue Statement


In [37]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

1
2
4
5
6


In [38]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry


In [40]:
for i in range(0,10,1):
    print(i)

0
1
2
3
4
5
6
7
8
9


use of pass statement 

In [41]:
for x in [0, 1, 2]:
  pass

Python Lambda

In [42]:
x = lambda a : a + 10
print(x(5))

15


In [43]:
x = lambda a, b : a * b
print(x(5, 6))

30


What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

In [44]:
import numpy as np #importing numpy libarary 


In [45]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


2d array 

In [46]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


Check Number of Dimensions?

In [48]:
print(arr.ndim)

2


ARRAY SLICING 

Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])


[1 2 3 4]


In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [55]:
print(arr.shape)

(7,)


In [58]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

newarr = arr.reshape(4, 3)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [63]:
import pandas as pd

df = pd.read_csv('/Users/adityakumar/Desktop/github/Techfuse_AIML /diabetes.csv')

print(df) 

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [64]:
import pandas as pd

df = pd.read_excel('PalmTree.xlsx')

print(df) 

     S.No.     Year            District    Area     Rainfall  Temprature  \
0        1   2004-5  Thiruvananthapuram   29263  1669.333333   27.603270   
1        2   2004-5              Kollam   36055  2471.500000   27.011790   
2        3   2004-5      Pathanamthitta   49221  2063.666667   26.777790   
3        4   2004-5           Alappuzha    4070  2635.000000   26.571483   
4        5   2004-5            Kottayam  112030  3554.666667   26.447336   
..     ...      ...                 ...     ...          ...         ...   
219    220  2019-20          Malappuram   42765  3300.000000   25.548929   
220    221  2019-20           Kozhikode   21930  3548.000000   25.602023   
221    222  2019-20             Wayanad   10770  2441.000000   25.297853   
222    223  2019-20              Kannur   48050  3903.000000   25.515444   
223    224  2019-20           Kasaragod   33995  4761.000000   25.542089   

     Production  
0         37915  
1         53233  
2         69094  
3          5577

In [65]:
print(df.head(3))

   S.No.    Year            District   Area     Rainfall  Temprature  \
0      1  2004-5  Thiruvananthapuram  29263  1669.333333    27.60327   
1      2  2004-5              Kollam  36055  2471.500000    27.01179   
2      3  2004-5      Pathanamthitta  49221  2063.666667    26.77779   

   Production  
0       37915  
1       53233  
2       69094  


In [67]:
print(df['Production'].head(10))

0     37915
1     53233
2     69094
3      5577
4    162409
5     52441
6     82603
7     22488
8     43353
9     42548
Name: Production, dtype: int64


In [68]:
df.iloc[19]

S.No.                20
Year             2005-6
District         Idukki
Area              38844
Rainfall         1271.0
Temprature    26.633695
Production        56330
Name: 19, dtype: object

In [69]:
df.iloc[10,2]

'Kozhikode'

In [70]:
df.shape

(224, 7)

In [71]:
df.isna().sum()

S.No.         0
Year          0
District      0
Area          0
Rainfall      0
Temprature    0
Production    0
dtype: int64

In [72]:
df.drop(['Area'], inplace=True, axis=1) #this is for dropiing a coulumn named Area 

In [73]:
df.isna().sum()

S.No.         0
Year          0
District      0
Rainfall      0
Temprature    0
Production    0
dtype: int64

In [74]:
print(df)

     S.No.     Year            District     Rainfall  Temprature  Production
0        1   2004-5  Thiruvananthapuram  1669.333333   27.603270       37915
1        2   2004-5              Kollam  2471.500000   27.011790       53233
2        3   2004-5      Pathanamthitta  2063.666667   26.777790       69094
3        4   2004-5           Alappuzha  2635.000000   26.571483        5577
4        5   2004-5            Kottayam  3554.666667   26.447336      162409
..     ...      ...                 ...          ...         ...         ...
219    220  2019-20          Malappuram  3300.000000   25.548929       39975
220    221  2019-20           Kozhikode  3548.000000   25.602023       22300
221    222  2019-20             Wayanad  2441.000000   25.297853        6200
222    223  2019-20              Kannur  3903.000000   25.515444       44820
223    224  2019-20           Kasaragod  4761.000000   25.542089       31365

[224 rows x 6 columns]


In [ ]:
df.dropna(axis=0,inplace=True) #removes all null rows with null values 